# Generated by Django 5.0 on 2025-06-18 11:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CodeSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('language', models.CharField(choices=[('cpp', 'C++'), ('py', 'Python')], default='cpp', max_length=3)),
                ('code_path', models.TextField()),
                ('input_path', models.TextField()),
                ('output_path', models.TextField(blank=True, null=True)),
                ('created_t', models.DateTimeField(auto_now=True)),
                ('compiled_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='QUEUED', max_length=32)),
                ('exec_time_ms', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
