# Generated by Django 5.0 on 2025-06-18 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compiler', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='codesubmission',
            old_name='compiled_at',
            new_name='completed_at',
        ),
        migrations.RenameField(
            model_name='codesubmission',
            old_name='created_t',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='codesubmission',
            name='error_path',
            field=models.TextField(blank=True, null=True),
        ),
    ]
