# Generated by Django 5.0 on 2025-06-18 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compiler', '0002_rename_compiled_at_codesubmission_completed_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codesubmission',
            name='created_at',
        ),
    ]
